WoW/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WoW.Models.ViewModels.User;
using WoW.Services;

namespace WoW.Web.Controllers
{
    public class UserController : Controller
    {
        private UserService userService;

        public UserController()
        {
            this.userService = new UserService();
        }

        // GET: User info
        [HttpGet]
        [Authorize(Roles = "User, Admin")]
        public ActionResult Info()
        {
            string userName = this.User.Identity.Name;
            ProfileVM user = this.userService.GetUser(userName);

            return this.View(user);
            
        }

        //POST: User info
        [HttpPost]
        [Authorize(Roles = "User, Admin")]
        public ActionResult Info(ProfileVM userDetails)
        {
            if (this.ModelState.IsValid)
            {
                var user = User.Identity.Name;
                this.userService.AddInfo(userDetails, user);
                return this.RedirectToAction("Info");
            }

            return this.View();
        }
        
    }
}

WoW/Controllers/WordController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WoW.Models.EntityModels;
using WoW.Models.ViewModels.Words;
using WoW.Services;


namespace WoW.Web.Controllers
{
    [Authorize(Roles ="User, Admin")]
    [RoutePrefix("word")]
    public class WordController : Controller
    {
        private WordService wordService;

        public WordController()
        {
            this.wordService = new WordService();
        }
        
        // GET: Word/Add
        public ActionResult Add()
        {
            
            return View();
        }

        // POST: Word/Add
        [HttpPost]
        [Authorize(Roles = "User, Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Add([Bind(Include ="Name, Description" )] AddWordVM word)
        {
            
            if (this.ModelState.IsValid)
            {
                //var user = System.Web.HttpContext.Current.User.Identity.GetUserName();
                var user = User.Identity.Name;
                this.wordService.AddWord(word, user); 
                return this.RedirectToAction("GetWordsOfUser");
            }

            return this.View();
        }

        
        [Authorize(Roles = "User, Admin")]
        public ActionResult GetWordsOfUser()
        {
            string userName = User.Identity.Name;
            IEnumerable<AllWordsOfUser> awou = this.wordService.GetWordsOfUserByName(userName);
            return this.View(awou);
        }

        public ActionResult TransferWords(int id)
        {
            this.wordService.TransferWords(id);
            return RedirectToAction("GetWordsOfUser");
        }

        // GET: Word/Edit/5
        [HttpGet, Route("edit/{id}")]
        [Authorize(Roles = "User, Admin")]
        public ActionResult Edit(int id)
        {
            string userName = User.Identity.Name;
            AddWordVM wordForEdit = this.wordService.GetSpecificWord(id);
            if (wordForEdit == null)
            {
                return HttpNotFound();
            }
            return this.PartialView("_Edit", wordForEdit);
        }

        // POST: Word/Edit/5
        [HttpPost]
        [Authorize(Roles = "User, Admin")]
        public ActionResult Edit([Bind(Include = "Name, Description")] AddWordVM word, int id)
        {
            if (this.ModelState.IsValid)
            {
                this.wordService.EditWord(word, id);
                return RedirectToAction("GetWordsOfUser");
            }
            return View(word);
        }

        // GET: Word/Delete/5
        [HttpGet, Route("delete/{id}")]
        [Authorize(Roles = "User, Admin")]
        public ActionResult Delete(int id)
        {
            AddWordVM wordForDelete = this.wordService.GetSpecificWord(id);
            if (wordForDelete == null)
            {
                return HttpNotFound();
            }
            
            return this.PartialView("_Delete", wordForDelete);
        }

        // POST: Word/Delete/5
        [HttpPost]
        [Authorize(Roles = "User, Admin")]
        public ActionResult Delete([Bind(Include = "Name, Description")] string id)
        {
            if (this.ModelState.IsValid)
            {
                this.wordService.DeleteWord(id);
                return RedirectToAction("GetWordsOfUser");
            }
            return RedirectToAction("GetWordsOfUser");
        }

        // GET: QandA/Create
        public ActionResult Search()
        {
            return View();
        }

        // POST: QandA/Create
        [HttpPost]
        public ActionResult Search([Bind(Include = "Word, Content")] SearchedWordVM sWord)
        {
            if (this.ModelState.IsValid)
            {
                IEnumerable<SearchedWordVM> allResults = this.wordService.SearchWord(sWord);
                //var serializer = new JavaScriptSerializer();
                //var jsonWords = serializer.Serialize(all);
                //return Json(new { result = "Redirect", url = Url.Action("AllQuestionsOfUsers", "QandA") });
                // return Json(new { error = true, message = RenderViewToString(PartialView("_SearchResult", sWord).ToString(), sWord)});
                //return Json(new { wordsData = jsonWords });
                return PartialView("_SearchResult", allResults);
            }
            
            return this.View();
        }
    }

}

WoW/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Свят от думи", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("Admin"))
                    {
                    <li>@Html.ActionLink("Админ", "Index", "Admin")</li>
                    }
                    <li>@Html.ActionLink("Търсене", "Search", "Word")</li>
                    <li>@Html.ActionLink("Добави дума", "Add", "Word")</li>
                    <li>@Html.ActionLink("Запитване", "AddQuestion", "QandA")</li>
                    <li>@Html.ActionLink("Всички въпроси", "AllQuestionsOfUsers", "QandA")</li>
                    
                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Моят профил <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("За мен", "Info", "User")</li>
                            <li>@Html.ActionLink("Моите думи", "GetWordsOfUser", "Word")</li>
                            <li>@Html.ActionLink("Моите въпроси", "AllQuestionsOfUsers", "QandA")</li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Свят от думи</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>